---
- name: Update my.cnf to allow emojis in the database
  copy:
    src: mysql/my.cnf
    dest: /etc/my.cnf
- name: Configure Git
  copy:
    src: git/.gitconfig
    dest: ~/.gitconfig
- name: Add Time Machine backup script
  copy:
    src: timemachine/backup.sh
    dest: ~/backup.sh

# Uncomment this if you want to allow remote connections to mysql
# - name: Get folder name for MySQL in homebrew
#   find:
#     paths: /usr/local/Cellar/mysql/
#     file_type: directory
#     patterns: "8.*"
#   register: file_name
# - name: Copy plist file to Homebrew cellar path
#   copy:
#     src: mysql/homebrew.mxcl.mysql.plist
#     dest: "{{ file_name.files[0].path }}/homebrew.mxcl.mysql.plist"
